[theme] 
primaryColor = "#1f77b4" 
backgroundColor = "#A6B0FF" 
secondaryBackgroundColor = "#CDC4FF"
textColor = "#FFFFFF" 
font = "sans serif"


[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
