[theme] 
primaryColor = "#1f77b4" 
backgroundColor = "#4820C9" 
secondaryBackgroundColor = "#4B46E0"
textColor = "#FFFFFF" 
font = "sans serif"


[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
