[theme] 
primaryColor = "#1f77b4" 
backgroundColor = "#FAFAFA" 
secondaryBackgroundColor = "#E6E6E6"
textColor = "#000000" 
font = "sans serif"


[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
