[theme]
primaryColor = "#1F77B4"              # Main accent color (blue)
backgroundColor = "#A6B0FF"           # App background color (soft lavender blue)
secondaryBackgroundColor = "#ADE1FF"  # Sidebar / widget background
textColor = "#262730"                 # Text color (dark gray)
font = "sans serif"                   # Font style (simple and clean)


[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
