[theme]
primaryColor = "#1f77b4"
backgroundColor = "#A6B0FF"
secondaryBackgroundColor = "#ADE1FF"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
