[theme] 
primaryColor = "#1f77b4" 
backgroundColor = "#0E0885" 
secondaryBackgroundColor = "#5B4185"
textColor = "#FFFFFF" 
font = "sans serif"


[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
